# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Aug 27 09:46:30 2025
# ------------------------------------------------

package:
  name: micromamba
  version: 2.3.2
source:
  - url: https://github.com/mamba-org/mamba/archive/refs/tags/2.3.2.tar.gz
    sha256: c969d189b0263218467b9e3b8922fcad8f7023bd8b5a981edc37e0da27cf953f
    folder: mamba
build:
  number: '0'
  string: '0'
  ignore_run_exports_from:
    - fmt
    - gcc_linux-64 14.*
    - gxx_linux-64 14.*
    - libarchive-minimal-static
    - libcurl
    - libsolv
    - openssl
    - spdlog
    - zlib
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.44 h4bf12b8_1
    - binutils_linux-64 2.44 h4852527_1
    - bzip2 1.0.8 h4bc722e_7
    - c-ares 1.34.5 hb9d3cd8_0
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - cmake 3.31.6 h74e3db0_0
    - gcc_impl_linux-64 14.3.0 hd9e9e21_4
    - gcc_linux-64 14.3.0 h1382650_11
    - gxx_impl_linux-64 14.3.0 he663afc_4
    - gxx_linux-64 14.3.0 ha7acb78_11
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - keyutils 1.6.3 hb9d3cd8_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.44 h1423503_1
    - libcurl 8.14.1 h332b0f4_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libexpat 2.7.1 hecca717_0
    - libgcc 15.1.0 h767d61c_4
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_104
    - libgcc-ng 15.1.0 h69a702a_4
    - libgomp 15.1.0 h767d61c_4
    - liblzma 5.8.1 hb9d3cd8_2
    - libnghttp2 1.64.0 h161d5f1_0
    - libsanitizer 14.3.0 hd08acf3_4
    - libssh2 1.11.1 hcf80075_0
    - libstdcxx 15.1.0 h8f9b012_4
    - libstdcxx-devel_linux-64 14.3.0 h85bb3a7_104
    - libstdcxx-ng 15.1.0 h4852527_4
    - libuv 1.51.0 hb03c661_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - ninja 1.13.1 h171cf75_0
    - openssl 3.5.2 h26f9b46_0
    - rhash 1.4.6 hb9d3cd8_1
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
    - zstd 1.5.7 hb8e6e7a_2
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - c-ares 1.34.5 hb9d3cd8_0
    - c-ares-static 1.34.5 hb9d3cd8_0
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - cli11 2.5.0 h3f2d84a_0
    - cpp-expected 1.1.0 hff21bea_1
    - fmt 11.2.0 h07f6e7f_0
    - keyutils 1.6.3 hb9d3cd8_0
    - krb5 1.21.3 h659f571_0
    - krb5-static 1.21.3 h659f571_0
    - libarchive-minimal-static 3.8.1 lgpl_he1c5e00_0
    - libcurl 8.14.1 h332b0f4_0
    - libcurl-static 8.14.1 h332b0f4_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libev-static 4.33 hd590300_2
    - libgcc 15.1.0 h767d61c_4
    - libgcc-ng 15.1.0 h69a702a_4
    - libgomp 15.1.0 h767d61c_4
    - liblzma 5.8.1 hb9d3cd8_2
    - liblzma-devel 5.8.1 hb9d3cd8_2
    - liblzma-static 5.8.1 hbcc6ac9_2
    - libnghttp2 1.64.0 h161d5f1_0
    - libnghttp2-static 1.64.0 h766bdaa_0
    - libopenssl-static 3.5.2 hb03c661_0
    - libsolv 0.7.35 h9463b59_0
    - libsolv-static 0.7.35 hf0c0ed0_0
    - libssh2 1.11.1 hcf80075_0
    - libssh2-static 1.11.1 hcf80075_0
    - libstdcxx 15.1.0 h8f9b012_4
    - libstdcxx-ng 15.1.0 h4852527_4
    - libzlib 1.3.1 hb9d3cd8_2
    - lz4-c 1.10.0 h5888daf_1
    - lz4-c-static 1.10.0 ha770c72_1
    - ncurses 6.5 h2d0b736_3
    - nlohmann_json 3.12.0 h3f2d84a_0
    - openssl 3.5.2 h26f9b46_0
    - reproc-cpp-static 14.2.5.post0 h5888daf_0
    - reproc-static 14.2.5.post0 hb9d3cd8_0
    - simdjson 3.13.0 h84d6215_0
    - simdjson-static 3.13.0 h1a2810e_0
    - spdlog 1.15.3 h6dc744f_1
    - xz-static 5.8.1 hbcc6ac9_2
    - yaml-cpp-static 0.8.0 h3f2d84a_0
    - zlib 1.3.1 hb9d3cd8_2
    - zstd 1.5.7 hb8e6e7a_2
    - zstd-static 1.5.7 h574f1f8_2
  run:
    - __glibc >=2.17,<3.0.a0
test:
  commands:
    - test -f "${PREFIX}/bin/micromamba"
    - test ! -f "${PREFIX}/etc/profile.d/mamba.sh"
    - micromamba --help
    - export MAMBA_ROOT_PREFIX="$(mktemp -d)"
    - micromamba create -n test --override-channels -c conda-forge --yes python=3.9
    - '"${MAMBA_ROOT_PREFIX}/envs/test/bin/python" --version'
    - '"${MAMBA_ROOT_PREFIX}/envs/test/bin/python" -c "import os"'
about:
  home: https://github.com/mamba-org/mamba
  license_file:
    - CLI11_LICENSE.txt
    - CURL_LICENSE.txt
    - C_ARES_LICENSE.txt
    - FMT_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - LIBEV_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
    - LIBOPENSSL_3_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
    - REPROC_LICENSE.txt
    - SPDLOG_LICENSE.txt
    - TL_EXPECTED_LICENSE.txt
    - ZLIB_LICENSE.txt
    - ZSTD_LICENSE.txt
    - mamba/LICENSE
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
  dev_url: https://github.com/mamba-org/mamba
extra:
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - jjerphan
    - mariusvniekerk
    - pavelzw
    - wolfv
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250827.2.1
  remote_url: https://github.com/conda-forge/micromamba-feedstock
  sha: 26d3de5edb5c8408f83a26663717d2010f2e0f09
