name: nets-scrna
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.1.4
  - scanpy=1.9.8
  - anndata=0.9.2
  - scipy=1.11.4
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - h5py=3.10.0
  - zarr=2.16.1
  - numcodecs=0.12.1
  - numexpr=2.8.7
  - pip
  - pip:
      - harmonypy==0.0.9
      - scrublet==0.2.3
      - doubletdetection==4.2
